#pragma once
#include "Utils.hpp"

#include <glad/gl.h>

#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtc/type_ptr.hpp>

#include <memory>
#include <vector>
#include <fstream>
#include <sstream>
#include <unordered_map>

namespace Core
{
    /// One GPU vertex: position, normal, and UV, matching the vertex attribute layout `Mesh::setup` uploads (locations 0/1/2).
    struct Vertex
    {
        glm::vec3 position;
        glm::vec3 normal;
        glm::vec2 texCoords;
        // glm::vec4 color;  -- add if you need per-vertex color
    };

    /**
     * @brief Owns a GPU vertex/index buffer set (VAO/VBO/EBO) for one drawable mesh.
     *
     * Non-copyable (it owns live GPU resources) but movable. Construction is
     * private — use one of the `Create` factories, which return `nullptr`
     * instead of throwing if GPU/file setup fails.
     */
    class Mesh
    {
    public:
        // --- Factory ---

        /// @brief Builds a mesh directly from pre-assembled vertex/index data.
        /// @return A new Mesh, or `nullptr` if construction failed.
        static std::shared_ptr<Mesh> Create(const std::string &tag, const std::vector<Vertex> &vertices, const std::vector<unsigned int> &indices, GLenum drawMode = GL_TRIANGLES);

        /**
         * @brief Builds a mesh from a flat position-only float array.
         *
         * Normals are not supplied — they're computed by accumulating face
         * normals at each shared vertex and normalizing (smooth shading),
         * rather than expected from the caller.
         * @return A new Mesh, or `nullptr` if construction failed.
         */
        static std::shared_ptr<Mesh> Create(const std::string &tag, const std::vector<GLfloat> &vertices, const std::vector<GLuint> &indices, GLenum drawMode = GL_TRIANGLES);

        /**
         * @brief Loads a mesh from a Wavefront OBJ file.
         *
         * Supports `v`/`vn`/`vt`/`f` lines with `v`, `v//vn`, or `v/vt/vn`
         * face-index forms. If the file has no `vn` data, flat normals are
         * generated by expanding to one unshared vertex per index — this
         * gives each triangle a clean per-face normal but means more
         * vertices than the source OBJ. Faces that aren't triangles are
         * skipped with a warning, not triangulated.
         * @param filename Path to the `.obj` file, resolved relative to the process's working directory (run from the project root).
         * @return A new Mesh, or `nullptr` if the file couldn't be opened or produced no vertices.
         */
        static std::shared_ptr<Mesh> Create(const std::string &filename, GLenum drawMode = GL_TRIANGLES);

        ~Mesh();

        // Non-copyable (owns GPU resources)
        Mesh(const Mesh &) = delete;
        Mesh &operator=(const Mesh &) = delete;

        // Movable
        Mesh(Mesh &&other) noexcept;
        Mesh &operator=(Mesh &&other) noexcept;

        // --- Rendering ---
        void bind() const;
        void unbind() const;
        void draw() const; // binds, draws

        // --- Accessors ---
        unsigned int getVertexCount() const { return vertexCount; }
        unsigned int getTriangleCount() const { return indexCount / 3; }
        GLenum getDrawMode() const { return drawMode; }

    private:
        Mesh(const std::string &tag, const std::vector<Vertex> &vertices, const std::vector<unsigned int> &indices, GLenum drawMode);
        Mesh(const std::string &tag, const std::vector<GLfloat> &vertices, const std::vector<GLuint> &indices, GLenum drawMode);

        void setup(const std::vector<Vertex> &vertices, const std::vector<unsigned int> &indices);
        void destroy();

        std::string tag_;

        GLuint VAO = 0;
        GLuint VBO = 0;
        GLuint EBO = 0;

        unsigned int vertexCount = 0;
        unsigned int indexCount = 0;
        GLenum drawMode = GL_TRIANGLES;
    };
}
