#pragma once
#include "Utils.hpp"

#include <glad/gl.h>

#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtc/type_ptr.hpp>

#include <memory>
#include <vector>
#include <limits>
#include <fstream>
#include <sstream>
#include <filesystem>
#include <unordered_map>

namespace Forge
{
    /// One GPU vertex: position, normal, and UV, matching the vertex attribute layout `Mesh::setup` uploads (locations 0/1/2).
    struct Vertex
    {
        glm::vec3 position;
        glm::vec3 normal;
        glm::vec2 texCoords;

        bool operator==(const Vertex &other) const
        {
            return position == other.position && normal == other.normal && texCoords == other.texCoords;
        }
        // glm::vec4 color;  -- add if you need per-vertex color
    };

    /// Result of parsing OBJ geometry into GPU-ready vertex/index data, before any GPU resource exists.
    struct ParsedMeshData
    {
        std::vector<Vertex> vertices;
        std::vector<unsigned int> indices;

        bool operator==(const ParsedMeshData &other) const
        {
            return vertices == other.vertices && indices == other.indices;
        }
    };

    /// One `usemtl` group's worth of parsed OBJ geometry (see `Mesh::ParseObjFileGroups`).
    /// `materialName` is the raw `usemtl` name as written in the file (empty string for
    /// faces that appear before the first `usemtl` line, or in a file with none at all) —
    /// it's a lookup key for the caller to resolve into a real Material, not a Material itself.
    struct ParsedMeshGroup
    {
        std::string materialName;
        ParsedMeshData mesh;
    };

    class Mesh;

    /// One `usemtl` group's worth of GPU-ready geometry (see `Mesh::CreateGroups`).
    struct MeshGroup
    {
        std::string materialName;
        std::shared_ptr<Mesh> mesh;
    };

    /**
     * @brief Owns a GPU vertex/index buffer set (VAO/VBO/EBO) for one drawable mesh.
     *
     * Non-copyable (it owns live GPU resources) but movable. Construction is
     * private — use one of the `Create` factories, which return `nullptr`
     * instead of throwing if GPU/file setup fails.
     */
    class Mesh
    {
    public:
        // --- Factory ---

        /// @brief Builds a mesh directly from pre-assembled vertex/index data.
        /// @return A new Mesh, or `nullptr` if construction failed.
        static std::shared_ptr<Mesh> Create(const std::string &tag, const std::vector<Vertex> &vertices, const std::vector<unsigned int> &indices, GLenum drawMode = GL_TRIANGLES);

        /**
         * @brief Builds a mesh from a flat position-only float array.
         *
         * Normals are not supplied — they're computed by accumulating face
         * normals at each shared vertex and normalizing (smooth shading),
         * rather than expected from the caller.
         * @return A new Mesh, or `nullptr` if construction failed.
         */
        static std::shared_ptr<Mesh> Create(const std::string &tag, const std::vector<GLfloat> &vertices, const std::vector<GLuint> &indices, GLenum drawMode = GL_TRIANGLES);

        /**
         * @brief Loads a mesh from a Wavefront OBJ file.
         *
         * Supports `v`/`vn`/`vt`/`f` lines with `v`, `v//vn`, or `v/vt/vn`
         * face-index forms. If the file has no `vn` data, flat normals are
         * generated by expanding to one unshared vertex per index — this
         * gives each triangle a clean per-face normal but means more
         * vertices than the source OBJ. Faces that aren't triangles are
         * skipped with a warning, not triangulated.
         * @param filename Path to the `.obj` file, resolved relative to the process's working directory (run from the project root).
         * @return A new Mesh, or `nullptr` if the file couldn't be opened or produced no vertices.
         */
        static std::shared_ptr<Mesh> Create(const std::string &filename, GLenum drawMode = GL_TRIANGLES);

        /**
         * @brief Loads a Wavefront OBJ file that uses `usemtl` to mark multiple material
         *        groups, producing one GPU Mesh per group instead of one for the whole file.
         *
         * The referenced `mtllib`, if any, is never opened — a `usemtl` name is only used
         * as a grouping/lookup key here, not resolved into real material parameters; the
         * caller maps each returned `materialName` to an actual `Material` itself (e.g. via
         * `ResourceManager::LoadMaterial`). Faces before the first `usemtl` line (or every
         * face, in a file with none at all) land in a single group keyed by an empty string.
         * @param filename Path to the `.obj` file, resolved relative to the process's working directory (run from the project root).
         * @return One `MeshGroup` per distinct `usemtl` name, in first-appearance order; empty if the file couldn't be opened or produced no vertices.
         */
        static std::vector<MeshGroup> CreateGroups(const std::string &filename, GLenum drawMode = GL_TRIANGLES);

        /**
         * @brief Parses Wavefront OBJ geometry from a stream into vertex/index data, generating
         *        flat per-face normals if the source has none.
         *
         * Pure CPU logic - touches no GPU resources - split out of `Create(filename)` specifically
         * so it can be unit tested without a GL context. Takes a stream rather than a filename so
         * tests can pass an in-memory `std::istringstream` instead of a real file on disk.
         *
         * Implemented in terms of `ParseObjFileGroups`: if the source has more than one
         * `usemtl` group, they're merged back into a single combined vertex/index buffer
         * (material boundaries are dropped) so this function's return type/behavior stays
         * exactly what it was before group support existed.
         * @param input Stream containing OBJ-format text.
         * @param sourceName Used only for warning/log messages (e.g. the original filename).
         * @return Parsed vertex/index data.
         * @throws std::runtime_error if the stream produced no vertices.
         */
        static ParsedMeshData ParseObjFile(std::istream &input, const std::string &sourceName);

        /**
         * @brief Parses Wavefront OBJ geometry from a stream into one `ParsedMeshGroup` per
         *        `usemtl` name, generating flat per-face normals (per group) if the source
         *        has no `vn` data at all.
         *
         * Pure CPU logic, same rationale as `ParseObjFile` (unit-testable without a GL
         * context). `v`/`vn`/`vt` indexing is shared across the whole file as normal OBJ
         * semantics require — only face-to-material association is grouped.
         * @param input Stream containing OBJ-format text.
         * @param sourceName Used only for warning/log messages (e.g. the original filename).
         * @return One group per distinct `usemtl` name, in first-appearance order.
         * @throws std::runtime_error if the stream produced no vertices.
         */
        static std::vector<ParsedMeshGroup> ParseObjFileGroups(std::istream &input, const std::string &sourceName);

        ~Mesh();

        // Non-copyable (owns GPU resources)
        Mesh(const Mesh &) = delete;
        Mesh &operator=(const Mesh &) = delete;

        // Movable
        Mesh(Mesh &&other) noexcept;
        Mesh &operator=(Mesh &&other) noexcept;

        // --- Rendering ---
        void bind() const;
        void unbind() const;
        void draw() const; // binds, draws

        // --- Accessors ---
        unsigned int getVertexCount() const { return vertexCount; }
        unsigned int getTriangleCount() const { return indexCount / 3; }
        GLenum getDrawMode() const { return drawMode; }

        glm::vec3 GetLowerBounds() const { return boundsMin; }
        glm::vec3 GetUpperBounds() const { return boundsMax; }

    private:
        Mesh(const std::string &tag, const std::vector<Vertex> &vertices, const std::vector<unsigned int> &indices, GLenum drawMode);
        Mesh(const std::string &tag, const std::vector<GLfloat> &vertices, const std::vector<GLuint> &indices, GLenum drawMode);

        void setup(const std::vector<Vertex> &vertices, const std::vector<unsigned int> &indices);
        void destroy();

        std::string tag_;

        GLuint VAO = 0;
        GLuint VBO = 0;
        GLuint EBO = 0;

        glm::vec3 boundsMin = glm::vec3(std::numeric_limits<float>::max());
        glm::vec3 boundsMax = glm::vec3(std::numeric_limits<float>::lowest());

        unsigned int vertexCount = 0;
        unsigned int indexCount = 0;
        GLenum drawMode = GL_TRIANGLES;

        void ComputeBounds(const std::vector<Vertex> &vertices);
    };
}
